source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-robots'
gem 'nokogiri'
gem 'oj', '~> 3.10'
gem 'spyke', '~> 5.3'
gem 'spyke-kaminari', '~> 0.0.6'
