source 'https://rubygems.org'

gem 'middleman', '~> 4.3'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-robots'
gem 'nokogiri'
gem 'oj', '~> 3.13'
gem 'spyke', '~> 6.1.2'
gem 'spyke-kaminari', '~> 0.0.6'
gem 'pry'